theme:

  layer:

    qfed1:
      gxout: grid
      cmark: 9
      digsiz: 0.08
      ccolor: 255 165 0
      cthick: 5
      expr: maskout(_biomass, _biomass-0.00000008)
      
    qfed2:
      gxout: grid
      cmark: 8
      digsiz: 0.08
      ccolor: 0 0 0
      cthick: 5
      expr: maskout(_biomass, _biomass-0.00000008)

    qfed3:
      gxout: grid
      cmark: 9
      digsiz: 0.090
      ccolor: 255 165 0
      cthick: 5
      expr: maskout(_biomass, _biomass-0.0000000007)
      zorder: -15

    qfed4:
      gxout: grid
      cmark: 8
      digsiz: 0.090
      ccolor: 0 0 0
      cthick: 5
      expr: maskout(_biomass, _biomass-0.0000000007)
      zorder: -15
