EIC_fire_dir: /discover/nobackup/dao_ops/jardizzo/EIC_fires
EIC_pub_dir: /discover/nobackup/projects/gmao/yotc/pub/fp/.internal/SVS/EIC_fires
ShortWAVE_dir: /discover/nobackup/projects/gmao/yotc/pub/fp/.internal/ShortWAVE
EIC_fire_source: $EIC_fire_dir/data/eonet/eonet_%Y%m%d/eonet_%Y%m%d.yml

max_events: 1
plot_domain_size: [14.0, 7.0]
stat_domain_size: [0.5, 0.5]

playlist: &PLAYLIST
  smoke:
  # title: 'Surface Smoke (BC+OC) [ug m`a-3`n]'
    title: 'Carbon Aerosol and Organic Carbon'
    content: SurfaceSmokeGEOSCF
    cbar: smoke.cbar.png
    levels: [0]
  wind10m:
  # title: '10-meter Wind Speed (m/s)'
    title: '10-meter Wind Speed'
    content: WindSpeed10mGEOS
    cbar: wind10m.cbar.png
    levels: [0]
  rhmin:
  # title: '24hr Minimum Relative Humidity (%)'
    title: '24hr Minimum Relative Humidity'
    content: RHMin24hrGEOS
    cbar: rhmin.cbar.png
    levels: [0]
# t2mmax:
# # title: '24hr Maximum 2-Meter Temperature (`aO`nC)'
#   title: '24hr Maximum 2-Meter Temperature'
#   content: T2mMax24hrGEOS-FP
#   cbar: t2mmax.cbar.png
#   levels: [0]
# gwettop:
#   title: 'Surface Soil Wetness'
#   content: GWETTopGEOS-FP
#   cbar: gwettop.cbar.png
#   levels: [0]
  bc:
    title: 'Black Carbon'
    content: BlackCarbonGEOS2km
    cbar: bc.cbar.png
    levels: [0]

statistics: &STATISTICS
  gwettop:
    levels: [0]
  t2mmax:
    levels: [0]
  wind10m:
    levels: [0]
  rhmin:
    levels: [0]
  pm25sfc:
    levels: [0]
  cosfc:
    levels: [0]
  no2sfc:
    levels: [0]
  o3sfc:
    levels: [0]

fire_monitor: &MONITOR
  fire_monitor:
    content: FireMonitorGEOS
    levels: [0]

base_images: &BASE
  pre_script: source $INSTALL_PATH/wxmap_modules
  theme: eic_fires_regional
  config: $EIC_fire_dir/events/Y%Y/M%m/D%d/src/event.yml
  playlist: *PLAYLIST
  stream: GEOS
  lights_off: 1
  plot_only: 1
  fullframe: 1
  geometry: 2048x1024
  fcst_dt: P0D
  start_dt: -P12D
  end_dt: PT24H
# start_dt: PT0H
# end_dt: PT0H
  t_deltat: PT1H
  oname: $EIC_fire_dir/events/Y%%Y/M%%m/D%%d/base/$region.$field.%Y%m%dT%H%M%S.png

stats:
  <<: *BASE
  playlist: *STATISTICS
  theme: eic_fires_stats
  config: $EIC_fire_dir/events/Y%Y/M%m/D%d/src/stat.yml
  oname: $EIC_fire_dir/events/Y%%Y/M%%m/D%%d/stats/$region.$field.stat

monitor:
  <<: *BASE
  playlist: *MONITOR
  console: $EIC_fire_dir/src/fire_monitor_all.png
  oname: $EIC_fire_dir/events/Y%%Y/M%%m/D%%d/final/$fire_name.nasa.gmao.geos.analysis.fire_monitor.%Y-%m-%dT%H:%M:%S.png

final_images: &FINAL
  <<: *BASE
  font_color: 255 255 255
  srcdir: $EIC_fire_dir/src
  fire_box_size: $stat_domain_size
  places_file: $EIC_fire_dir/src/places.json
  bold_name: $EIC_fire_dir/src/helr65w.ttf
  font_name: $EIC_fire_dir/src/helr65w.ttf
  date_box_name: $EIC_fire_dir/src/date-box-curved-corner-500x100px.png
  logo_box_name: $EIC_fire_dir/src/logo-box-curved-corner-350x75px.png
  nasa_logo_name: $EIC_fire_dir/src/nasa-logo.png
  gmao_logo_name: $EIC_fire_dir/src/gmao-logo-white.png
  fire_icon: $EIC_fire_dir/src/fire_icon.png
  oname: $EIC_fire_dir/events/Y%%Y/M%%m/D%%d/final/$fire_name.nasa.gmao.geos.analysis.$field.%Y-%m-%dT%H:%M:%S.png

movies: &MOVIES
  <<: *BASE
  modules: ffmpeg_modules
  playlist: *PLAYLIST
  frame_rate: 12
  frame_size: 2048x1024
  quality: 25
  codec: libx264
  oname: $EIC_fire_dir/events/Y%Y/M%m/D%d/mp4/$fire_name.nasa.gmao.geos.analysis.$field.%Y%m%d.mp4

publish: &PUBLISH
  <<: *BASE
  ntasks: 5
  oname: $EIC_pub_dir/Y%Y/M%m/D%d/$fire_name.nasa.gmao.geos.analysis.$field.%Y%m%d.mp4

publish_latest:
  <<: *BASE
  ntasks: 5
  oname: $EIC_pub_dir/latest/$fire_name.$content.%Y%m%d.mp4

shortwave:

  final_images:
    <<: *FINAL
    oname: $EIC_fire_dir/events/Y%%Y/M%%m/D%%d/ShortWAVE/final/$fire_name.nasa.gmao.geos.analysis.$field.%Y-%m-%dT%H:%M:%S.png
#   legend: $EIC_fire_dir/src/EIC_fire_legend.png

  movies:
    <<: *MOVIES
    oname: $EIC_fire_dir/events/Y%Y/M%m/D%d/ShortWAVE/mp4/$fire_name.nasa.gmao.geos.analysis.$field.%Y%m%d.mp4

  publish:
    <<: *PUBLISH
    ntasks: 5
    oname: $ShortWAVE_dir/wildfires/EIC/Y%Y/M%m/D%d/$fire_name.nasa.gmao.geos.analysis.$field.%Y%m%d.mp4

clean_movies:
  playlist: *PLAYLIST
  fcst_dt: PT0H
  start_dt: -P5D
  end_dt: P0D
  t_deltat: P1D

clean_images:
  playlist: *PLAYLIST
  fcst_dt: PT0H
  start_dt: -P30D
  end_dt: -P17D
  t_deltat: PT1H
